# Change these first
owner: janeapp
repo: partner-sandbox-uptime

sites:
  - name: Wibbi Sandbox
    url: https://wibbi.jane.qa
  - name: Fullscript Sandbox
    url: https://fullscript.jane.qa
  - name: S3 Sandbox
    url: https://s3.jane.qa

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: janeapp/partner-sandbox-uptime
  name: Partner Sandbox Availability
  introTitle: "**Partner Sandbox Availability**"
  introMessage: This is a status page for the Partner Sandbox services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
